import { test, expect } from "../../../src/frontend/test-kit";

test("real API: signup, admin decision, cookie permissions, CRUD, profile and password", async ({ browser }) => {
  test.setTimeout(60000);
  const email = "browser-" + Date.now() + "@example.com";
  const memberContext = await browser.newContext({ reducedMotion: "reduce" });
  const adminContext = await browser.newContext({ reducedMotion: "reduce" });
  const member = await memberContext.newPage();
  const admin = await adminContext.newPage();
  try {
    await member.goto("http://127.0.0.1:4173/admin");
    await member.getByRole("button", { name: "Ainda não tem conta? Cadastre-se" }).click();
    await member.getByLabel("Nome completo").fill("Ana Browser");
    await member.getByLabel("Celular").fill("11999999999");
    await member.getByLabel("E-mail", { exact: true }).fill(email);
    await member.getByLabel("Nova senha", { exact: true }).fill("browser-member-password");
    await member.getByLabel("Confirmar senha", { exact: true }).fill("browser-member-password");
    await member.getByRole("button", { name: "Criar conta", exact: true }).click();
    await member.getByLabel("Código recebido por e-mail").fill("12345678");
    await member.getByRole("button", { name: "Confirmar cadastro" }).click();
    await member.getByRole("button", { name: "Pular por enquanto" }).click();
    await expect(member.getByText("Seu acesso está em análise")).toBeVisible();
    const cookies = await memberContext.cookies();
    expect(cookies.find(cookie => cookie.name === "nexo_access_token")?.httpOnly).toBe(true);
    expect(await member.evaluate(() => document.cookie.includes("nexo_access_token"))).toBe(false);
    expect(await member.evaluate(async () => (await fetch("/api/clients")).status)).toBe(403);
    await admin.goto("http://127.0.0.1:4173/admin");
    await admin.getByLabel("E-mail", { exact: true }).fill("owner@example.com");
    await admin.getByLabel("Senha", { exact: true }).fill("initial-admin-password");
    await admin.getByRole("button", { name: "Entrar no painel" }).click();
    await admin.getByRole("button", { name: "Ver solicitações" }).click();
    await admin.getByRole("button", { name: "Autorizar", exact: true }).click();
    await admin.getByRole("button", { name: "Confirmar decisão" }).click();
    await expect(admin.getByText("Acesso autorizado.")).toBeVisible();
    await member.getByRole("button", { name: "Verificar aprovação" }).click();
    await expect(member.getByRole("heading", { name: "Clientes", exact: true })).toBeVisible();
    await member.setViewportSize({ width: 360, height: 780 });
    await member.getByRole("button", { name: "Abrir menu do painel" }).click();
    await member.getByRole("dialog").getByRole("button", { name: "Membros", exact: true }).click();
    await expect(member.getByRole("dialog")).toHaveCount(0);
    await expect(member.getByText("Ana Browser", { exact: true })).toBeVisible();
    expect(await member.evaluate(async () => {
      const response = await fetch("/api/members");
      return (await response.json()).every((row: Record<string, unknown>) => Object.keys(row).sort().join(",") === "id,name,role");
    })).toBe(true);
    await member.getByRole("button", { name: "Abrir menu do painel" }).click();
    await member.getByRole("dialog").getByRole("button", { name: "Clientes", exact: true }).click();
    await member.setViewportSize({ width: 1280, height: 720 });
    await member.getByRole("button", { name: "Novo cliente" }).click();
    const dialog = member.getByRole("dialog");
    await dialog.getByLabel("Nome / empresa").fill("Loja Browser");
    await dialog.getByLabel("Nicho", { exact: true }).fill("Varejo");
    await dialog.getByRole("button", { name: "Salvar cliente" }).click();
    await expect(member.getByText("Cliente salvo.")).toBeVisible();
    await member.getByRole("button", { name: "Editar Loja Browser" }).click();
    await dialog.getByLabel("Situação do contrato").selectOption("true");
    await dialog.getByRole("button", { name: "Salvar cliente" }).click();
    await expect(member.locator("[data-slot=badge]").filter({ hasText: "Fechado" })).toBeVisible();
    await member.getByRole("button", { name: "Excluir Loja Browser" }).click();
    await member.getByRole("button", { name: "Confirmar exclusão" }).click();
    await expect(member.getByText("Cliente removido.")).toBeVisible();
    await member.getByRole("button", { name: "Meu perfil", exact: true }).click();
    await member.getByLabel("Nome completo").fill("Ana Atualizada");
    await member.getByRole("button", { name: "Salvar perfil" }).click();
    await expect(member.getByText("Perfil atualizado.")).toBeVisible();
    await member.getByLabel("Escolher foto").setInputFiles({
      name: "photo.png", mimeType: "image/png",
      buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAGUlEQVR4nGNsYGhgIAUwkaR6VMOohiGlAQBCPQEgiSD+iQAAAABJRU5ErkJggg==", "base64"),
    });
    await expect(member.getByRole("img", { name: "Foto de Ana Atualizada" })).toBeVisible();
    await member.getByRole("button", { name: "Remover foto" }).click();
    await expect(member.getByText("Foto removida.")).toBeVisible();
    await member.getByLabel("Senha atual", { exact: true }).fill("browser-member-password");
    await member.getByLabel("Nova senha", { exact: true }).fill("browser-updated-password");
    await member.getByLabel("Confirmar nova senha").fill("browser-updated-password");
    await member.getByRole("button", { name: "Atualizar senha", exact: true }).click();
    await expect(member.getByRole("button", { name: "Entrar no painel" })).toBeVisible();
    await member.getByLabel("E-mail", { exact: true }).fill(email);
    await member.getByLabel("Senha", { exact: true }).fill("browser-updated-password");
    await member.getByRole("button", { name: "Entrar no painel" }).click();
    await expect(member.getByRole("heading", { name: "Clientes", exact: true })).toBeVisible();
    await admin.getByRole("button", { name: "Gerenciar membros", exact: true }).click();
    await admin.getByRole("button", { name: "Editar membro Ana Atualizada" }).click();
    await admin.getByRole("dialog").getByLabel("Cargo", { exact: true }).selectOption("admin");
    await admin.getByRole("button", { name: "Salvar membro" }).click();
    await expect(admin.getByText("Membro atualizado.")).toBeVisible();
    // Changing privileges invalidates the previous HttpOnly session.
    await member.getByRole("button", { name: "Atualizar clientes" }).click();
    await expect(member.getByRole("button", { name: "Entrar no painel" })).toBeVisible();
    await member.getByLabel("E-mail", { exact: true }).fill(email);
    await member.getByLabel("Senha", { exact: true }).fill("browser-updated-password");
    await member.getByRole("button", { name: "Entrar no painel" }).click();
    await member.getByRole("button", { name: "Gerenciar membros", exact: true }).click();
    await expect(member.getByRole("button", { name: "Excluir membro Ana Atualizada" })).toBeDisabled();
    await member.getByRole("button", { name: "Meu perfil", exact: true }).click();
    await member.getByRole("button", { name: "Apagar minha conta" }).click();
    await member.getByRole("button", { name: "Enviar código de exclusão" }).click();
    await member.getByLabel("Código de exclusão recebido por e-mail").fill("87654321");
    await member.getByRole("button", { name: "Confirmar exclusão da minha conta" }).click();
    await expect(member.getByRole("button", { name: "Entrar no painel" })).toBeVisible();
    await admin.getByRole("button", { name: "Atualizar membros" }).click();
    await expect(admin.getByRole("button", { name: "Editar membro Ana Atualizada" })).toHaveCount(0);
    expect(await member.evaluate(async () => (await fetch("/api/auth/me")).status)).toBe(401);
  } finally { await memberContext.close(); await adminContext.close(); }
});
